# Generated by Django 5.1.3 on 2024-11-27 17:04

import autoslug.fields
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=product.models.category_image_path)),
                ('menuicon', models.CharField(max_length=200)),
            ],
        ),
    ]
