# Generated by Django 5.1.3 on 2024-11-27 17:54

import product.models
import product.valid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='menuicon',
            field=models.CharField(help_text='fontawsomedan al.!!!', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.category_image_path, validators=[product.valid.valid_image_extension, product.valid.valid_size]),
        ),
    ]
